services:
  postgres:
    image: postgres:15
    environment: {POSTGRES_USER: user, POSTGRES_PASSWORD: password, POSTGRES_DB: music}
    ports: [ "5432:5432" ]
    volumes: [./data/db:/docker-entrypoint-initdb.d]